# Generated by Django 5.0.1 on 2024-01-11 00:28

import django.db.models.deletion
from django.db import migrations, models

# initial data for ChatFormat and OpenaiModel
def create_default_data(apps, schema_editor):
    ChatFormat = apps.get_model('backend', 'ChatFormat')
    OpenaiModel = apps.get_model('backend', 'OpenaiModel')
    ChatFormat.objects.create(chat_name='chatml', chat_description='<|im_start|> system \n {system_prompt} <|im_end|> \n <|im_start|> {user_prompt} <|im_end|> \n<|im_start|> assistant', default=True)
    ChatFormat.objects.create(chat_name='llama-chat', chat_description='<s>[INST] <<SYS>>\n {system_prompt} \n<</SYS>> \n\n {user_prompt}[/INST]', default=False)
    ChatFormat.objects.create(chat_name='mistral-instruct', chat_description='<s>[INST]{system_prompt}\n{user_prompt} [/INST]', default=False)
    OpenaiModel.objects.create(model_name='gpt-3.5-turbo-1106', context_length='16k', accepts_json=True, default=True)
    OpenaiModel.objects.create(model_name='gpt-4-1106-preview', context_length='128k', accepts_json=True, default=False)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('chat_description', models.CharField(max_length=255)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='OpenaiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, max_length=60, unique=True)),
                ('context_length', models.CharField(blank=True, max_length=60, null=True)),
                ('accepts_json', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source_url', models.CharField(max_length=255)),
                ('llm', models.TextField(blank=True, max_length=255, null=True)),
                ('llm_output', models.TextField(blank=True, max_length=1000, null=True)),
                ('success', models.BooleanField(default=False)),
                ('llm_turns', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoggedDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('source_url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, db_index=True, default='No title', max_length=255)),
                ('publication_date', models.DateField(blank=True, db_index=True, null=True)),
                ('overview', models.TextField(blank=True, db_index=True, null=True)),
                ('summary', models.TextField(blank=True, db_index=True, null=True)),
                ('summary_type', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('llm', models.TextField(blank=True, max_length=255, null=True)),
                ('summary_embedding', models.JSONField(blank=True, null=True)),
                ('default_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.docimage')),
            ],
        ),
        migrations.AddField(
            model_name='docimage',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loggeddoc'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_index=True, max_length=255)),
                ('name_embedding', models.JSONField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loggeddoc')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('name_embedding', models.JSONField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loggeddoc')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_embedding', models.JSONField(blank=True, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.loggeddoc')),
            ],
        ),

        migrations.RunPython(create_default_data, reverse_code=migrations.RunPython.noop)
    ]
